name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the latest code
    - name: Checkout the code
      uses: actions/checkout@v2

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Adjust version as needed

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        cd app
        npm install

    # Step 4: Run Tests
    - name: Run tests
      run: |
        cd app
        npm test  # Ensure you have Jest tests configured
        
    # find package.json
    - name: Find package.json path
      id: find_package
      run: echo "PACKAGE_PATH=$(find ${{ github.workspace }} -type f -name 'package.json' | head -n 1)" >> $GITHUB_ENV
    - name: Debug package.json path
      run: echo "Found package.json at $PACKAGE_PATH"
      
    # Step 5: Build the application
    - name: Build the application
      run: |
        cd /home/runner/work/Nodjs/Nodjs/app
        npm run build  # Ensure this step exists in package.json

    - name: Check for dist folder
      run: |
        echo "Checking for dist folder..."
        find . -type d -name "dist"
        if [ -d "dist" ]; then
        echo "dist folder found"
        else
        echo "dist folder not found"
        fi

    # Step 6: Verify build output
    - name: Verify build output
      run: |
        ls -R dist

    # Step 7: Setup SSH for deployment
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    # Step 8: Copy files to EC2
    - name: Copy files to EC2
      run: |
        scp -i ~/.ssh/id_rsa -r dist/* ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/nodejs

    # Step 9: Start or Restart the app using PM2
    - name: Start the app using PM2
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} "cd /home/ubuntu/nodejs && pm2 start server.js --name 'node-app' || pm2 restart node-app"

